In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('bodyPerformanceI.csv')
df

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
0,24.0,F,152.4,42.5,23.4,57.0,112.0,27.4,14.2,50.0,184.0,C
1,27.0,F,162.1,70.9,35.7,97.0,148.0,30.6,11.0,42.0,157.0,D
2,23.0,M,173.7,68.3,13.6,76.0,137.0,47.7,16.5,48.0,208.0,C
3,31.0,M,168.2,70.5,15.5,82.0,145.0,39.6,19.9,66.0,264.0,C
4,25.0,M,175.1,64.8,6.9,65.0,118.0,42.0,19.8,49.0,252.0,B
...,...,...,...,...,...,...,...,...,...,...,...,...
7010,21.0,M,179.6,78.6,16.3,64.0,118.0,54.1,25.9,58.0,248.0,B
7011,56.0,M,166.8,64.0,21.4,75.0,132.0,50.7,13.0,36.0,197.0,B
7012,26.0,M,177.4,78.3,14.0,74.0,115.0,53.3,15.3,63.0,234.0,A
7013,49.0,M,177.2,83.0,19.7,98.0,158.0,40.2,14.9,50.0,203.0,C
7014,43.0,F,161.5,49.9,29.8,79.0,155.0,21.0,16.5,23.0,146.0,C

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7015 entries, 0 to 7014
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      7015 non-null   float64
 1   gender                   7015 non-null   object
 2   height_cm                7015 non-null   float64
 3   weight_kg                7015 non-null   float64
 4   body fat_%               7015 non-null   float64
 5   diastolic                7015 non-null   float64
 6   systolic                 7015 non-null   float64
 7   gripForce                7015 non-null   float64
 8   sit and bend forward_cm  7015 non-null   float64
 9   sit-ups counts           7015 non-null   float64
 10  broad jump_cm            7015 non-null   float64
 11  class                    7015 non-null   object
dtypes: float64(10), object(2)
memory usage: 657.8+ KB

In [7]:
df.isnull().sum()

age                        0
gender                     0
height_cm                  0
weight_kg                  0
body fat_%                 0
diastolic                  0
systolic                   0
gripForce                  0
sit and bend forward_cm    0
sit-ups counts             0
broad jump_cm              0
class                      0
dtype: int64

In [15]:
df['gender'].value_counts()

M    4552
F    2463
Name: gender, dtype: int64

In [16]:
df['class'].value_counts()

B    3222
C    2565
A     617
D     611
Name: class, dtype: int64